version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - storage

  redis2:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - storage

  url_shorter:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_DSNS: "redis://redis:6379, redis://redis2:6379"
      SERVICE_URL: "http://0.0.0.0:8080"
      SERVICE_PORT: "8080"
    networks:
      - storage

networks:
  storage:
